-- Upgrade the initial Game Hub schema already deployed in this Supabase project.
-- The migration removes the old browser-write policies and replaces them with scoped RPCs.
alter table public.profiles add column if not exists role text not null default 'player' check (role in ('player','admin'));
alter table public.profiles add column if not exists current_streak integer not null default 0 check (current_streak >= 0);
alter table public.profiles add column if not exists longest_streak integer not null default 0 check (longest_streak >= 0);
alter table public.profiles add column if not exists reward_ready boolean not null default false;
create table if not exists public.daily_activity (id bigint generated always as identity primary key,user_id uuid references auth.users(id) on delete cascade,guest_id text,activity_date date not null default current_date,first_played_at timestamptz not null default now(),last_played_at timestamptz not null default now(),check ((user_id is not null) <> (guest_id is not null)));
create unique index if not exists daily_activity_user_day on public.daily_activity(user_id,activity_date) where user_id is not null;
create unique index if not exists daily_activity_guest_day on public.daily_activity(guest_id,activity_date) where guest_id is not null;
create index if not exists game_sessions_user_idx on public.game_sessions(user_id,started_at desc);

-- Align the original three placeholders with the bundled files (the existing table is empty of sessions).
update public.games set id='space-sprint',title='Space Sprint',description='A fast placeholder for your first HTML game.',path='/games/space-sprint.html' where id='game-1';
update public.games set id='puzzle-lab',title='Puzzle Lab',description='A thoughtful placeholder for your next challenge.',path='/games/puzzle-lab.html' where id='game-2';
update public.games set id='arcade-dash',title='Arcade Dash',description='A bright placeholder for an arcade favourite.',path='/games/arcade-dash.html' where id='game-3';

alter table public.profiles enable row level security; alter table public.games enable row level security; alter table public.game_sessions enable row level security; alter table public.daily_activity enable row level security;
drop policy if exists sessions_insert_public on public.game_sessions; drop policy if exists sessions_update_owner on public.game_sessions; drop policy if exists games_public_read on public.games; drop policy if exists profiles_insert_own on public.profiles; drop policy if exists profiles_select_own on public.profiles; drop policy if exists profiles_update_own on public.profiles;
revoke all on public.profiles,public.games,public.game_sessions,public.daily_activity from anon,authenticated;
grant select on public.games to anon,authenticated; grant select on public.profiles to authenticated;
create policy "active games public" on public.games for select to anon,authenticated using (active);
create policy "own profile only" on public.profiles for select to authenticated using (id=(select auth.uid()));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name) values(new.id,coalesce(nullif(left(new.raw_user_meta_data->>'display_name',40),''),'Player')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin') $$;
create or replace function public.refresh_streak(p_user uuid) returns void language plpgsql security definer set search_path=public as $$ declare n integer; begin with o as (select activity_date,row_number() over(order by activity_date desc) rn from public.daily_activity where user_id=p_user) select count(*) into n from o where activity_date=current_date-(rn::integer-1); update public.profiles set current_streak=n,longest_streak=greatest(longest_streak,n),reward_ready=(n>=7) where id=p_user; end; $$;
create or replace function public.public_games() returns table(slug text,title text,description text) language sql stable security definer set search_path=public as $$ select id,title,coalesce(description,'') from public.games where active order by created_at $$;
create or replace function public.start_game_session(p_game_slug text,p_guest_token uuid) returns uuid language plpgsql security definer set search_path=public as $$ declare g text; sid uuid; u uuid:=(select auth.uid()); begin select id into g from public.games where id=p_game_slug and active; if g is null then raise exception 'Unknown game'; end if; if u is null and p_guest_token is null then raise exception 'Guest token required'; end if; insert into public.game_sessions(game_id,user_id,guest_id) values(g,u,case when u is null then p_guest_token::text else null end) returning id into sid; return sid; end; $$;
create or replace function public.heartbeat_game_session(p_session_id uuid,p_guest_token uuid) returns integer language plpgsql security definer set search_path=public as $$ declare u uuid:=(select auth.uid()); owner_id uuid; guest text; elapsed integer; begin update public.game_sessions set duration_seconds=duration_seconds+least(90,greatest(0,extract(epoch from clock_timestamp()-last_heartbeat_at)::integer)),last_heartbeat_at=clock_timestamp() where id=p_session_id and ended_at is null and (user_id=u or (user_id is null and guest_id=p_guest_token::text)) returning user_id,guest_id into owner_id,guest; if not found then raise exception 'Session not found'; end if; if owner_id is not null then insert into public.daily_activity(user_id,last_played_at) values(owner_id,clock_timestamp()) on conflict(user_id,activity_date) where user_id is not null do update set last_played_at=excluded.last_played_at; perform public.refresh_streak(owner_id); else insert into public.daily_activity(guest_id,last_played_at) values(guest,clock_timestamp()) on conflict(guest_id,activity_date) where guest_id is not null do update set last_played_at=excluded.last_played_at; end if; return 1; end; $$;
create or replace function public.end_game_session(p_session_id uuid,p_guest_token uuid) returns void language plpgsql security definer set search_path=public as $$ begin update public.game_sessions set ended_at=clock_timestamp() where id=p_session_id and ended_at is null and (user_id=(select auth.uid()) or (user_id is null and guest_id=p_guest_token::text)); end; $$;
create or replace function public.leaderboard(p_limit integer default 10) returns table(display_name text,play_seconds bigint,current_streak integer) language sql stable security definer set search_path=public as $$ select p.display_name,coalesce(sum(s.duration_seconds),0)::bigint,p.current_streak from public.profiles p left join public.game_sessions s on s.user_id=p.id group by p.id order by 2 desc,p.current_streak desc limit least(greatest(p_limit,1),100) $$;
create or replace function public.admin_dashboard() returns jsonb language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'Administrator access required' using errcode='42501'; end if; return jsonb_build_object('total_players',(select count(*) from public.profiles),'daily_active_players',(select count(distinct user_id) from public.daily_activity where activity_date=current_date and user_id is not null),'total_play_seconds',(select coalesce(sum(duration_seconds),0) from public.game_sessions),'reward_ready_players',(select count(*) from public.profiles where reward_ready),'players',(select coalesce(jsonb_agg(x order by x.play_seconds desc),'[]'::jsonb) from (select p.display_name,s.play_seconds,s.session_count,a.active_days,p.current_streak,p.reward_ready from public.profiles p left join lateral(select coalesce(sum(duration_seconds),0)::bigint play_seconds,count(*) session_count from public.game_sessions where user_id=p.id)s on true left join lateral(select count(*) active_days from public.daily_activity where user_id=p.id)a on true order by s.play_seconds desc limit 100)x)); end; $$;
revoke all on function public.is_admin(),public.refresh_streak(uuid),public.handle_new_user(),public.public_games(),public.start_game_session(text,uuid),public.heartbeat_game_session(uuid,uuid),public.end_game_session(uuid,uuid),public.leaderboard(integer),public.admin_dashboard() from public,anon,authenticated;
revoke all on function public.admin_game_stats() from public,anon,authenticated;
grant execute on function public.public_games(),public.start_game_session(text,uuid),public.heartbeat_game_session(uuid,uuid),public.end_game_session(uuid,uuid),public.leaderboard(integer) to anon,authenticated;
grant execute on function public.admin_dashboard() to authenticated;
